version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bangaride-frontend
    ports:
      - "5100:5100"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 